### ISSUE TITLE
Also accept JWT as request object

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [b2cm/id_ideal_wallet#3]
https://github.com/b2cm/id_ideal_wallet/blob/ad1880d6214c1f587601556d14255b5b200d73f8/lib/functions/oidc_handler.dart#L292

It is hidden quite deep down in the spec, but the requestObject must be encoded in a signed JWT in the current state.

https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-authorization-request second sentence follow two links of RFC

Maybe support both for now?

**Comment by F-Node-Karlsruhe** [comment]
see other implementations https://github.com/Sphereon-Opensource/SIOP-OID4VP/blob/develop/src/request-object/RequestObject.ts#L52

**Comment by SaOtto** [comment]
I've noticed aswell that the request object should be a JWT. Support for it will be part of the next release.

**Comment by SaOtto** [comment]
Fixed with release 2.4.15
